/**
 * Pakistan provinces/territories and major cities for the checkout address
 * form. Not exhaustive — these back a searchable combobox that also accepts
 * free text, so anywhere not listed can still be typed in directly.
 */

export const PK_REGIONS: string[] = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad Capital Territory",
  "Gilgit-Baltistan",
  "Azad Jammu & Kashmir",
];

export const PK_CITIES: string[] = [
  "Lahore",
  "Karachi",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Sukkur",
  "Bahawalpur",
  "Sargodha",
  "Sheikhupura",
  "Jhelum",
  "Rahim Yar Khan",
  "Gujrat",
  "Kasur",
  "Okara",
  "Mardan",
  "Abbottabad",
  "Mingora",
  "Dera Ghazi Khan",
  "Nawabshah",
  "Larkana",
  "Mirpur Khas",
  "Chiniot",
  "Kamoke",
  "Sadiqabad",
  "Burewala",
  "Jacobabad",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Bahawalnagar",
  "Muzaffarabad",
  "Mirpur (AJK)",
  "Gilgit",
  "Skardu",
  "Chaman",
  "Turbat",
  "Khuzdar",
  "Dera Ismail Khan",
  "Kohat",
  "Swabi",
  "Nowshera",
  "Charsadda",
  "Attock",
  "Chakwal",
  "Jhang",
  "Mianwali",
  "Vehari",
  "Toba Tek Singh",
  "Khanewal",
  "Pakpattan",
  "Layyah",
  "Rajanpur",
  "Sahiwal",
  "Wah Cantt",
  "Taxila",
  "Hafizabad",
  "Narowal",
  "Mandi Bahauddin",
  "Nankana Sahib",
  "Kot Addu",
  "Kotli",
  "Haripur",
  "Battagram",
  "Chitral",
].sort((a, b) => a.localeCompare(b));
